"""
bootstrap-hadrons.py — clone, configure, build, and install Hadrons against
an already-installed Grid into the directory where this script is run.

Usage
-----
    python3 bootstrap-hadrons.py [OPTIONS]

Run `python3 bootstrap-hadrons.py --help` for a full list of flags.

Assumes you have already run bootstrap-grid.py (or have Grid installed
somewhere) so that a valid Grid prefix exists.

Everything is installed under:

    <cwd>/
        deps/                      ← shared with bootstrap-grid.py
            src/
                hadrons/           ← cloned Hadrons source
                hadrons-build/     ← out-of-source Hadrons build
        hadrons-install/           ← final Hadrons install prefix
"""

from __future__ import annotations

import argparse
import multiprocessing
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────
# Helpers  (identical to bootstrap-grid.py)
# ──────────────────────────────────────────────────────────────────────

def run(cmd: str | list[str], *, cwd: Path | None = None, env: dict | None = None) -> None:
    """Run a shell command, streaming output, aborting on failure."""
    if isinstance(cmd, str):
        cmd = shlex.split(cmd)
    merged_env = {**os.environ, **(env or {})}
    print(f"\n>>> {' '.join(cmd)}")
    subprocess.check_call(cmd, cwd=cwd, env=merged_env)


def ensure_dir(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p


def which(name: str) -> str | None:
    return shutil.which(name)


# ── Terminal title + stage progress ─────────────────────────────────

def _set_terminal_title(title: str) -> None:
    sys.stdout.write(f"\033]0;{title}\007")
    sys.stdout.flush()


class StageTracker:
    def __init__(self, steps: list[tuple[str, str]]) -> None:
        self._steps = steps
        self._total = len(steps)
        self._index: dict[str, int] = {key: i for i, (key, _) in enumerate(steps)}

    def begin(self, key: str) -> None:
        idx = self._index[key]
        num = idx + 1
        label = self._steps[idx][1]
        banner = f"[{num}/{self._total}] {label}"
        _set_terminal_title(f"Hadrons bootstrap {banner}")
        print(f"\n\033[1;36m==>\033[0m \033[1m{banner}\033[0m")

    def finish(self) -> None:
        _set_terminal_title("Hadrons bootstrap — done")
        print(f"\n\033[1;32m==>\033[0m \033[1mBootstrap complete "
              f"[{self._total}/{self._total}]\033[0m")


# ──────────────────────────────────────────────────────────────────────
# Compiler resolution  (mirrored from bootstrap-grid.py)
# ──────────────────────────────────────────────────────────────────────

LLVM_VERSION = "18.1.8"
NJOBS = str(multiprocessing.cpu_count())


def _find_system_compiler() -> tuple[str, str]:
    if which("gcc") and which("g++"):
        return "gcc", "g++"
    return "gcc", "g++"


def _install_prebuilt_llvm(deps_prefix: Path) -> Path:
    import platform
    machine = platform.machine().lower()
    if machine in ("x86_64", "amd64"):
        arch = "X64"
    elif machine in ("aarch64", "arm64"):
        arch = "ARM64"
    else:
        raise RuntimeError(f"No prebuilt LLVM binary available for {machine}")

    version = LLVM_VERSION
    src = ensure_dir(deps_prefix / "src" / "llvm")

    for d in src.iterdir():
        if d.is_dir() and (d / "bin" / "clang").exists():
            return d

    tarball_name = f"LLVM-{version}-Linux-{arch}.tar.xz"
    url = (f"https://github.com/llvm/llvm-project/releases/"
           f"download/llvmorg-{version}/{tarball_name}")
    tarball = src / tarball_name

    if not tarball.exists():
        run(["curl", "-fL", "-o", str(tarball), url])
    run(f"tar xf {tarball_name}", cwd=src)

    for d in src.iterdir():
        if d.is_dir() and (d / "bin" / "clang").exists():
            return d

    raise RuntimeError(
        "Extracted LLVM tarball but could not find bin/clang in any subdirectory."
    )


def _prepend_to_path(bindir: Path) -> None:
    os.environ["PATH"] = str(bindir) + os.pathsep + os.environ.get("PATH", "")


def _set_compiler_env(
    cc: str, cxx: str, deps_prefix: Path, *, extra_path: str | None = None,
) -> None:
    os.environ["CC"] = cc
    os.environ["CXX"] = cxx
    env_file = deps_prefix / "compiler.env"
    lines = ["# Auto-generated by bootstrap-hadrons — do not edit\n"]
    if extra_path:
        lines.append(f'export PATH="{extra_path}:${{PATH}}"\n')
    lines.append(f'export CC="{cc}"\n')
    lines.append(f'export CXX="{cxx}"\n')
    with open(env_file, "w") as f:
        f.writelines(lines)
    print(f"Wrote {env_file}")


def ensure_compiler(
    deps_prefix: Path, *, no_llvm: bool = False, jobs: str = NJOBS,
) -> tuple[str, str]:
    """Resolve C/C++ compilers.  Returns ``(cc, cxx)``."""
    if no_llvm:
        cc, cxx = _find_system_compiler()
        print(f"--no-llvm: using system compilers: {cc} / {cxx}")
        _set_compiler_env(cc, cxx, deps_prefix)
        return cc, cxx

    if which("clang") and which("clang++"):
        print(f"Found clang on PATH: {which('clang')}")
        _set_compiler_env("clang", "clang++", deps_prefix)
        return "clang", "clang++"

    try:
        print("\nclang not found on PATH — trying prebuilt LLVM download …")
        llvm_prefix = _install_prebuilt_llvm(deps_prefix)
        _prepend_to_path(llvm_prefix / "bin")
        print(f"Prebuilt LLVM ready: {llvm_prefix}")
        _set_compiler_env(
            "clang", "clang++", deps_prefix,
            extra_path=str(llvm_prefix / "bin"),
        )
        return "clang", "clang++"
    except (subprocess.CalledProcessError, RuntimeError, OSError) as exc:
        print(f"Prebuilt LLVM install failed: {exc}")

    cc, cxx = _find_system_compiler()
    print(f"\n{'!'*60}")
    print(f"WARNING: Could not install LLVM/Clang.")
    print(f"Falling back to system compilers: {cc} / {cxx}")
    print(f"{'!'*60}")
    _set_compiler_env(cc, cxx, deps_prefix)
    return cc, cxx


# ──────────────────────────────────────────────────────────────────────
# Grid installation verification
# ──────────────────────────────────────────────────────────────────────

def verify_grid(grid_prefix: Path) -> tuple[str | None, str | None]:
    """Abort early with a helpful message if Grid does not look installed.

    Returns ``(cxx, cc)`` as extracted from ``grid-config --cxx`` /
    ``grid-config --cc``, or ``(None, None)`` if not available.
    """
    grid_config = grid_prefix / "bin" / "grid-config"
    if not grid_config.exists():
        raise RuntimeError(
            f"Could not find {grid_config}.\n"
            f"Please build Grid first (run bootstrap-grid.py) or pass "
            f"--with-grid=<PREFIX> pointing to a valid Grid installation."
        )
    print(f"Found Grid installation: {grid_prefix}")
    # Print the Grid build summary so it appears in logs
    try:
        summary = subprocess.check_output(
            [str(grid_config), "--summary"], text=True,
        ).strip()
        print(f"\n{summary}\n")
    except subprocess.CalledProcessError:
        pass

    # Extract the compiler Grid was built with so we can warn about mismatches.
    grid_cxx: str | None = None
    grid_cc: str | None = None
    for flag, attr in (("--cxx", "grid_cxx"), ("--cc", "grid_cc")):
        try:
            val = subprocess.check_output(
                [str(grid_config), flag], text=True, stderr=subprocess.DEVNULL,
            ).strip()
            if val:
                locals()[attr]   # just reference it — set via the loop below
        except subprocess.CalledProcessError:
            pass
    # Simpler approach: run each query independently
    def _query(flag: str) -> str | None:
        try:
            out = subprocess.check_output(
                [str(grid_config), flag], text=True, stderr=subprocess.DEVNULL,
            ).strip()
            return out or None
        except (subprocess.CalledProcessError, FileNotFoundError):
            return None

    grid_cxx = _query("--cxx")
    grid_cc  = _query("--cc")

    if grid_cxx:
        print(f"Grid was built with CXX={grid_cxx}")
    if grid_cc:
        print(f"Grid was built with CC={grid_cc}")

    return grid_cxx, grid_cc


# ──────────────────────────────────────────────────────────────────────
# Hadrons builder
# ──────────────────────────────────────────────────────────────────────

def build_hadrons(args: argparse.Namespace, deps_prefix: Path,
                  grid_cxx: str | None = None, grid_cc: str | None = None) -> None:
    root = Path.cwd()
    hadrons_src   = deps_prefix / "src" / "hadrons"
    hadrons_build = deps_prefix / "src" / "hadrons-build"
    hadrons_install = root / "hadrons-install"
    grid_prefix = Path(args.with_grid)

    # ── Clone / update source ───────────────────────────────────────
    if not hadrons_src.exists():
        run(
            f"git clone --branch {args.hadrons_branch} "
            f"https://github.com/ctpeterson/Hadrons-BiFlow.git {hadrons_src}"
        )
    elif args.hadrons_pull:
        run("git pull", cwd=hadrons_src)

    # ── Autoconf bootstrap ──────────────────────────────────────────
    run("./bootstrap.sh", cwd=hadrons_src)

    # ── Out-of-source build directory ──────────────────────────────
    ensure_dir(hadrons_build)

    # ── Assemble configure command ──────────────────────────────────
    configure_cmd: list[str] = [str(hadrons_src / "configure")]

    configure_cmd.append(f"--prefix={hadrons_install}")
    configure_cmd.append(f"--with-grid={grid_prefix}")

    # ── Optional HDF5 override ──────────────────────────────────────
    # Hadrons uses HDF5 for its serialisation framework.
    # If the user supplies --with-hdf5, pass it; otherwise let Hadrons
    # pick up whatever was already visible when Grid was configured.
    if args.with_hdf5:
        configure_cmd.append(f"--with-hdf5={args.with_hdf5}")

    # ── Debug / optimisation ────────────────────────────────────────
    if args.debug:
        configure_cmd.append("--enable-debug=yes")

    # ── Compiler overrides ──────────────────────────────────────────
    # Prefer: explicit CLI flag > Grid's own compiler > environment default.
    # Grid and Hadrons MUST use the same OpenMP runtime (libomp vs libgomp);
    # mixing Clang-built Grid with GCC-built Hadrons causes __kmpc_* link errors.
    effective_cxx = args.cxx or grid_cxx
    effective_cc  = args.cc  or grid_cc

    if effective_cxx and effective_cxx != os.environ.get("CXX", ""):
        # Warn if the user's explicit choice differs from Grid's compiler
        if args.cxx and grid_cxx and args.cxx != grid_cxx:
            print(f"\n{'!'*60}")
            print(f"WARNING: --cxx={args.cxx} differs from the compiler Grid")
            print(f"         was built with ({grid_cxx}).")
            print(f"         OpenMP ABI mismatches will cause linker errors.")
            print(f"{'!'*60}\n")
        configure_cmd.append(f"CXX={effective_cxx}")
    elif os.environ.get("CXX"):
        configure_cmd.append(f"CXX={os.environ['CXX']}")

    if effective_cc:
        configure_cmd.append(f"CC={effective_cc}")
    elif os.environ.get("CC"):
        configure_cmd.append(f"CC={os.environ['CC']}")

    if args.mpicxx:
        configure_cmd.append(f"MPICXX={args.mpicxx}")
    if args.cxxflags:
        configure_cmd.append(f"CXXFLAGS={args.cxxflags}")
    if args.ldflags:
        configure_cmd.append(f"LDFLAGS={args.ldflags}")

    # ── Extra raw flags ─────────────────────────────────────────────
    if args.extra_configure_flags:
        configure_cmd.extend(shlex.split(args.extra_configure_flags))

    # ── Run configure ───────────────────────────────────────────────
    run(configure_cmd, cwd=hadrons_build)

    # ── Build & install ─────────────────────────────────────────────
    run(f"make -j{args.jobs}", cwd=hadrons_build)
    if args.run_tests:
        run(f"make -j{args.jobs} tests", cwd=hadrons_build)
        run("make check", cwd=hadrons_build)
    run("make install", cwd=hadrons_build)

    print(f"\n{'='*60}")
    print(f"Hadrons installed to: {hadrons_install}")
    print(f"{'='*60}\n")

    # ── Print usage hint ────────────────────────────────────────────
    print("To use this Hadrons install, set in your application's CMake / Makefile:")
    print(f"  HADRONS_PREFIX = {hadrons_install}")
    print(f"  GRID_PREFIX    = {grid_prefix}")
    print()
    print("Or load with pkg-config:")
    print(f"  export PKG_CONFIG_PATH={hadrons_install}/lib/pkgconfig:"
          f"{grid_prefix}/lib/pkgconfig:$PKG_CONFIG_PATH")


# ──────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Bootstrap Hadrons against an existing Grid installation.\n"
            "Run bootstrap-grid.py first to build Grid."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
examples:
  # Minimal build — uses ./grid-install (default Grid prefix from bootstrap-grid.py)
  python3 bootstrap-hadrons.py

  # Point at a custom Grid prefix
  python3 bootstrap-hadrons.py --with-grid /opt/grid

  # Use the system default compiler instead of LLVM/Clang
  python3 bootstrap-hadrons.py --no-llvm

  # Build with MPI wrappers
  python3 bootstrap-hadrons.py --mpicxx mpicxx

  # Debug build
  python3 bootstrap-hadrons.py --debug

  # Track a specific Hadrons branch / tag
  python3 bootstrap-hadrons.py --hadrons-branch feature/my-branch

  # Pass extra flags directly to Hadrons' configure
  python3 bootstrap-hadrons.py --extra-configure-flags="--enable-devel-headers=yes"
""",
    )

    # ── Grid ────────────────────────────────────────────────────────
    grid_grp = p.add_argument_group("Grid location")
    grid_grp.add_argument(
        "--with-grid", metavar="PREFIX",
        default=str(Path.cwd() / "grid-install"),
        help="Prefix of the Grid installation to build Hadrons against "
             "(default: ./grid-install, i.e. the output of bootstrap-grid.py)",
    )

    # ── Compiler ────────────────────────────────────────────────────
    comp = p.add_argument_group("compiler overrides")
    comp.add_argument("--no-llvm", action="store_true",
                      help="Do not attempt to install or use LLVM/Clang; use the "
                           "default system compiler (typically GCC) instead.")
    comp.add_argument("--cxx", metavar="COMPILER",
                      help="C++ compiler (default: inherits CC from env / compiler detection)")
    comp.add_argument("--cc", metavar="COMPILER",
                      help="C compiler")
    comp.add_argument("--mpicxx", metavar="COMPILER",
                      help="MPI C++ wrapper (e.g. mpicxx, mpiicpc)")
    comp.add_argument("--cxxflags", metavar="FLAGS",
                      help="Extra CXXFLAGS passed to configure")
    comp.add_argument("--ldflags", metavar="FLAGS",
                      help="Extra LDFLAGS passed to configure")

    # ── Optional dependencies ───────────────────────────────────────
    deps = p.add_argument_group("optional dependency overrides")
    deps.add_argument("--with-hdf5", metavar="PREFIX",
                      help="HDF5 prefix to pass to Hadrons configure "
                           "(only needed if different from Grid's HDF5)")

    # ── Debug ───────────────────────────────────────────────────────
    dbg = p.add_argument_group("debug / optimisation")
    dbg.add_argument("--debug", action="store_true",
                     help="Build with -g instead of -O2/-O3")

    # ── Build control ───────────────────────────────────────────────
    build = p.add_argument_group("build control")
    build.add_argument("--jobs", "-j", default=NJOBS, metavar="N",
                       help=f"Parallel make jobs (default: {NJOBS})")
    build.add_argument("--hadrons-branch", default="develop", metavar="BRANCH",
                       help="Hadrons-BiFlow git branch to clone (default: develop)")
    build.add_argument("--hadrons-pull", action="store_true",
                       help="Run git pull in an existing hadrons source checkout")
    build.add_argument("--run-tests", action="store_true",
                       help="Build and run Hadrons' test suite after compilation")

    # ── Escape hatch ────────────────────────────────────────────────
    p.add_argument("--extra-configure-flags", metavar="'FLAGS'",
                   help="Raw string appended verbatim to the configure invocation")

    return p.parse_args()


# ──────────────────────────────────────────────────────────────────────
# Stage list
# ──────────────────────────────────────────────────────────────────────

def _build_stage_list(args: argparse.Namespace) -> list[tuple[str, str]]:
    stages: list[tuple[str, str]] = [
        ("compiler", "Resolving compiler"),
        ("verify",   "Verifying Grid installation"),
        ("hadrons",  "Building Hadrons"),
    ]
    return stages


# ──────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    root = Path.cwd()
    deps_prefix = root / "deps"
    ensure_dir(deps_prefix)

    stages = StageTracker(_build_stage_list(args))

    # ── Resolve compiler ───────────────────────────────────────────
    stages.begin("compiler")
    cc, cxx = ensure_compiler(deps_prefix, no_llvm=args.no_llvm, jobs=args.jobs)
    print(f"Using CC={cc}  CXX={cxx}")

    # ── Verify Grid ────────────────────────────────────────────────
    stages.begin("verify")
    grid_cxx, grid_cc = verify_grid(Path(args.with_grid))

    # ── Build Hadrons ──────────────────────────────────────────────
    stages.begin("hadrons")
    build_hadrons(args, deps_prefix, grid_cxx=grid_cxx, grid_cc=grid_cc)

    stages.finish()


if __name__ == "__main__":
    main()
